version: "3.7"
services:
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_DB: matcha_db
      POSTGRES_USER: matcha_user
      POSTGRES_PASSWORD: matcha_password
    ports:
      - '5433:5432'
    volumes:
      - ./server/src/main/resources/sql:/docker-entrypoint-initdb.d
      - matcha-postgres:/var/lib/postgresql/data
  debug_node:
    image: node:latest
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    working_dir: /project/app
    command: yarn start
    ports:
      - '3001:3000'
    volumes:
      - .:/project


volumes:
  matcha-postgres:
  matcha-uploads: