apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: will-playground-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Tenagrim/git_ops_argocg_configs.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true